### ISSUE TITLE
language.dat.lua is outdated

### ISSUE THREAD

**Issue by mojca** [hyphenation/tex-hyphen#10]
In our repository we keep the file [language.dat.lua](https://github.com/hyphenation/tex-hyphen/blob/ac17146aaf95fc94b27507da066262f2243148ef/TL/texmf-dist/tex/generic/config/language.dat.lua) which hasn't been updated. We should either update it (not manually, but automatically) or remove it.

**Comment by reutenauer** [comment]
It is autogenerated in TeX Live by instructions in the `.tlpsrc` files, right?

**Comment by reutenauer** [comment]
Replying to myself: yes, it is, with the command `tlmgr generate language.dat.lua`.  It uses information in the `.tlspsrc` files, which in turn are created by `generate-tl-files.rb` in our repository.

**Comment by mojca** [comment]
What do you mean by 'none of the files in the repository are used by TeX Live'?

The `tlpsrc` files are usually directly copied from our repository into TeX Live, so we need to keep that file, it's super useful. The `language.dat` and `language.def` could in theory be auto-generated by `tlmgr`, but we don't currently have an easy way to call `tlmgr` to generate those files for us (maybe that's feasible to set up, I don't know). Those files are used when testing the format generation, so we certainly need them, at least for pdftex, xetex, xelatex, ptex, platex. We don't currently test lua(la)tex, so the lua table is not so useful at the moment.

**Comment by reutenauer** [comment]
Aaah, sorry, I of course didn’t mean _repository_; only the directory (`TL/texmf-dist/tex/generic/config`).  By “used by TeX Live” I meant to ask for confirmation that a standard installation doesn’t need these files since they are generated from the contents of the `.tlpsrc`.  Thanks for confirming that.

I’m not suggesting to remove them at all, but I’m reviewing and refactoring the code of the generator scripts (which I find messy and confusing, especially `generate-tl-files`, sorry); and I’ve just made a number of simplifications that resulted in small changes in the order of entries in `language.dat`; clearly that’s harmless.

I definitely want to have Travis run these kind of tests too, yes.

**Comment by reutenauer** [comment]
Actually it was quite easy to refactor and preserve the exact contents and `language.dat` and other files; it only took me ≈12 hours :-)
