### ISSUE TITLE
mul-Ethi patterns should be renamed to und-Ethi

### ISSUE THREAD

**Issue by roozbehp** [hyphenation/tex-hyphen#18]
The BCP 47 code "mul" is used to mark up text that contains more than one language. For text in *any* language written in the Ethiopic script, the correct code to use is "und-Ethi".

This is the text from BCP 47 itself (https://tools.ietf.org/html/bcp47):

The 'und' subtag might be useful for protocols that require a language tag to be provided or where a primary language subtag is required (such as in "und-Latn").  The 'und' subtag MAY also be useful when matching language tags in certain situations.

**Comment by reutenauer** [comment]
Thanks for the suggestion.  I saw that you retagged the patterns as `[und-Ethi]` in the Android repository, but I don’t quite agree: the patterns were developed for a small number of languages written using the Ethiopic script, not any language (we initially identified these languages as `[gez]` Ge‘ez and `[am]` Amharic).  The subtag `[mul]` may not be the best match but seemed to fit quite well according to the description (“we’d like to specify a list of languages but we can’t”); in any case, since the documented meaning of `[und-Ethi]` is “any linguistic content in the Ethiopic script”, this definitely sounds like the wrong tag.

**Comment by roozbehp** [comment]
If it's just for those two languages, then you can do the same you do for Hindi/Marathi or Bokmal/Nynorsk. Keep identical copies for those two languages only, so people wouldn't assume the patterns are useful for other languages written in the Ethiopic script.

**Comment by reutenauer** [comment]
I’m closing this, as it doesn’t seem we can come to an agreement, but thanks for the report!
